HTTP_PORT=25510
WS_PORT=25520
WS_LINES=1
CLIENT_PORT=11000
STREAM_PORT=10000
HTTP_CONCURRENCY=2
HTTP_PAGE_EXPIRE=10000
HTTP_TICK_LIM=500000
WS_TIMEOUT=300000
MDDS_TIMEOUT=10000
FPSS_TIMEOUT=10000
RECONNECT_WAIT=1000
MDDS_REGION=MDDS_NJ_HOSTS
FPSS_REGION=FPSS_NJ_HOSTS
MDDS_NJ_HOSTS=nj-a.thetadata.us:12000,nj-a.thetadata.us:12001,nj-b.thetadata.us:12000,nj-b.thetadata.us:12001
FPSS_NJ_HOSTS=nj-a.thetadata.us:20000,nj-a.thetadata.us:20001,nj-b.thetadata.us:20000,nj-b.thetadata.us:20001
