import { FastifyInstance, FastifyPluginOptions, FastifyReply } from 'fastify';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import * as z from 'zod/v4';
import { ManualOptionOrderService } from '../services/manual-option-order-service';
import { getGlobalSettings, resolveMcpTradingEnabled } from '../lib/settings-utils';

type McpConfig = {
  enabled: boolean;
};

function jsonToolResult(data: any) {
  return {
    content: [{ type: 'text' as const, text: JSON.stringify(data, null, 2) }],
    structuredContent: data
  };
}

async function getMcpConfig(fastify: FastifyInstance): Promise<McpConfig> {
  const settings = await getGlobalSettings((fastify as any).pg);
  return {
    enabled: resolveMcpTradingEnabled(settings)
  };
}

function reject(reply: FastifyReply, statusCode: number, message: string) {
  return reply.code(statusCode).send({
    jsonrpc: '2.0',
    error: { code: -32000, message },
    id: null
  });
}

function createTradingMcpServer(fastify: FastifyInstance, userId: number) {
  const server = new McpServer({
    name: 'options-trade-monitoring-trader',
    version: '1.0.0'
  });
  const service = new ManualOptionOrderService(fastify);

  server.registerTool('get_trading_guardrails', {
    title: 'Get Trading Guardrails',
    description: 'Return the configured trading user, account readiness, and validation rules for this MCP trading server.',
    annotations: {
      readOnlyHint: true,
      openWorldHint: false
    }
  }, async () => {
    return jsonToolResult(await service.getGuardrails(userId));
  });

  server.registerTool('get_option_quote', {
    title: 'Get Option Quote',
    description: 'Return the live IBKR quote used by guarded option order validation.',
    inputSchema: {
      symbol: z.string().trim().min(1).max(12).describe('Underlying ticker, for example SPY or QQQ.'),
      optionType: z.enum(['CALL', 'PUT']).describe('Option side.'),
      strike: z.number().positive().describe('Option strike price.'),
      expiration: z.string().trim().min(8).max(20).describe('Expiration date in YYYY-MM-DD format.')
    },
    annotations: {
      readOnlyHint: true,
      openWorldHint: true
    }
  }, async (input) => {
    const quote = await service.getOptionQuote(userId, {
      symbol: input.symbol,
      optionType: input.optionType,
      strike: input.strike,
      expiration: input.expiration
    });
    if (!quote) throw new Error('No live quote found for selected contract.');
    return jsonToolResult(service.toQuotePayload(quote));
  });

  server.registerTool('place_option_trade', {
    title: 'Place Option Trade',
    description: 'Submit a single-leg option opening order through SnapTrade after app-level quote, account, duplicate, and live-trading checks.',
    inputSchema: {
      clientOrderId: z.string().trim().min(8).max(120).describe('Stable idempotency key generated by the agent for this exact intended order.'),
      symbol: z.string().trim().min(1).max(12).describe('Underlying ticker, for example SPY or QQQ.'),
      optionType: z.enum(['CALL', 'PUT']).describe('Option side.'),
      action: z.enum(['BUY_TO_OPEN', 'SELL_TO_OPEN']).describe('Opening action. SELL_TO_OPEN eligibility is decided by the broker.'),
      strike: z.number().positive().describe('Option strike price.'),
      expiration: z.string().trim().min(8).max(20).describe('Expiration date in YYYY-MM-DD format.'),
      quantity: z.number().int().min(1).max(100).describe('Contract quantity.'),
      orderType: z.enum(['LIMIT', 'MARKET']).describe('Order type.'),
      premium: z.number().positive().optional().describe('Required for LIMIT orders; submitted as the exact limit price.'),
      underlyingStopPrice: z.number().positive().optional().describe('Optional underlying stop price for app risk tracking.')
    },
    annotations: {
      readOnlyHint: false,
      destructiveHint: true,
      openWorldHint: true
    }
  }, async (input) => {
    if (input.orderType === 'LIMIT' && (!input.premium || input.premium <= 0)) {
      throw new Error('premium is required for LIMIT orders and is submitted as the exact limit price.');
    }
    const result = await service.submit(userId, {
      clientOrderId: input.clientOrderId,
      source: 'mcp',
      symbol: input.symbol,
      optionType: input.optionType,
      action: input.action,
      strike: input.strike,
      expiration: input.expiration,
      quantity: input.quantity,
      orderType: input.orderType,
      limitPrice: input.orderType === 'LIMIT' ? input.premium : null,
      underlyingStopPrice: input.underlyingStopPrice || null
    });
    return jsonToolResult({
      success: result.success,
      reusedIdempotencyResult: Boolean(result.reusedIdempotencyResult),
      orderId: result.orderId,
      tradeId: result.tradeId,
      optionSymbol: result.optionSymbol,
      positionId: result.position?.id || null,
      positionStatus: result.position?.status || null,
      executionStatus: result.position?.execution_status || null,
      action: result.position?.entry_action || input.action,
      orderType: input.orderType
    });
  });

  return server;
}

export async function mcpRoutes(fastify: FastifyInstance, options: FastifyPluginOptions) {
  fastify.route({
    method: ['GET', 'POST', 'DELETE'],
    url: '/mcp',
    handler: async (request, reply) => {
      const config = await getMcpConfig(fastify);
      if (!config.enabled) return reject(reply, 503, 'MCP trading is disabled.');
      try {
        await request.jwtVerify();
      } catch {
        return reject(reply, 401, 'Unauthorized MCP trading request.');
      }
      const userId = Number((request as any).user?.id || 0);
      if (!Number.isInteger(userId) || userId <= 0) return reject(reply, 401, 'MCP JWT is missing a valid app user id.');

      const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
      const server = createTradingMcpServer(fastify, userId);
      let cleanedUp = false;
      const cleanup = async () => {
        if (cleanedUp) return;
        cleanedUp = true;
        await transport.close().catch((err) => {
          fastify.log.warn(`[MCP] Failed to close transport: ${err.message || String(err)}`);
        });
        await server.close().catch((err) => {
          fastify.log.warn(`[MCP] Failed to close server: ${err.message || String(err)}`);
        });
      };

      reply.raw.on('close', () => {
        cleanup().catch((err) => {
          fastify.log.warn(`[MCP] Cleanup failed: ${err.message || String(err)}`);
        });
      });

      try {
        await server.connect(transport);
        reply.hijack();
        await transport.handleRequest(request.raw as any, reply.raw as any, request.body);
      } catch (err: any) {
        fastify.log.error(`[MCP] Request failed: ${err.message || String(err)}`);
        if (!reply.raw.headersSent && !reply.raw.writableEnded) {
          reply.raw.writeHead(500, { 'Content-Type': 'application/json' });
          reply.raw.end(JSON.stringify({
            jsonrpc: '2.0',
            error: { code: -32603, message: 'Internal server error' },
            id: null
          }));
        }
        await cleanup();
      }
    }
  });
}
