#!/bin/sh
set -eu

JAR_PATH="/opt/thetadata/ThetaTerminal.jar"
CONFIG_FILE="${THETADATA_CONFIG_FILE:-/var/lib/thetadata/config_0.properties}"
LOG_DIRECTORY="${THETADATA_LOG_DIRECTORY:-/var/lib/thetadata/logs}"
FILE_DIRECTORY="${THETADATA_FILE_DIRECTORY:-/var/lib/thetadata/files}"
HTTP_PORT="${THETADATA_HTTP_PORT:-25510}"
WS_PORT="${THETADATA_WS_PORT:-25520}"
CLIENT_PORT="${THETADATA_CLIENT_PORT:-11000}"
STREAM_PORT="${THETADATA_STREAM_SOCKET_PORT:-10000}"

mkdir -p \
  "$(dirname "$CONFIG_FILE")" \
  "$LOG_DIRECTORY" \
  "$FILE_DIRECTORY" \
  /root/.theta \
  /root/ThetaData/ThetaTerminal \
  /root/.ThetaData/ThetaTerminal

cat > "$CONFIG_FILE" <<EOF
HTTP_PORT=${HTTP_PORT}
WS_PORT=${WS_PORT}
CLIENT_PORT=${CLIENT_PORT}
STREAM_PORT=${STREAM_PORT}
FILE_DIR=${FILE_DIRECTORY}
HTTP_CONCURRENCY=${THETADATA_HTTP_CONCURRENCY:-2}
WS_LINES=${THETADATA_WS_LINES:-1}
FPSS_QUEUE_DEPTH=${THETADATA_FPSS_QUEUE_DEPTH:-1000000}
HTTP_TICK_LIM=${THETADATA_HTTP_TICK_LIM:-500000}
MDDS_TIMEOUT=${THETADATA_MDDS_TIMEOUT:-10000}
FPSS_TIMEOUT=${THETADATA_FPSS_TIMEOUT:-10000}
RECONNECT_WAIT=${THETADATA_RECONNECT_WAIT:-1000}
MDDS_REGION=${THETADATA_MDDS_REGION:-MDDS_NJ_HOSTS}
FPSS_REGION=${THETADATA_FPSS_REGION:-FPSS_NJ_HOSTS}
EOF

if [ -n "${THETADATA_TERMINAL_ARGS:-}" ]; then
  exec java ${THETADATA_JAVA_OPTS:-} -jar "$JAR_PATH" ${THETADATA_TERMINAL_ARGS}
fi

if [ -n "${THETADATA_USERNAME:-}" ] && [ -n "${THETADATA_PASSWORD:-}" ]; then
  CREDS_FILE="/tmp/thetadata-creds.txt"
  {
    printf '%s\n' "$THETADATA_USERNAME"
    printf '%s\n' "$THETADATA_PASSWORD"
  } > "$CREDS_FILE"
  chmod 600 "$CREDS_FILE"
  exec java ${THETADATA_JAVA_OPTS:-} -jar "$JAR_PATH" --creds-file "$CREDS_FILE" --config "$CONFIG_FILE" --log-directory "$LOG_DIRECTORY"
fi

echo "ThetaData Terminal requires THETADATA_USERNAME and THETADATA_PASSWORD, or explicit THETADATA_TERMINAL_ARGS." >&2
echo "THETADATA_API_KEY is used by the backend API client, not as a ThetaTerminal launch argument." >&2
exit 64
